#include "BlueprintManager.h"
#include "Engine/Blueprint.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Misc/MessageDialog.h"
#include "HAL/PlatformFilemanager.h"
#include "HAL/PlatformFile.h"

UBlueprintManager::UBlueprintManager()
{
    UE_LOG(LogTemp, Warning, TEXT("?? BlueprintManager создан!"));
}

void UBlueprintManager::CreateAllBlueprints()
{
    UE_LOG(LogTemp, Warning, TEXT("=== ?? НАЧИНАЕМ СОЗДАНИЕ ВСЕХ BLUEPRINTS ==="));

    // Создаем папку для блюпринтов
    EnsureBlueprintFolderExists();

    // Получаем все классы проекта
    TArray<UClass*> ProjectClasses;
    GetAllProjectClasses(ProjectClasses);

    UE_LOG(LogTemp, Warning, TEXT("?? Найдено классов для создания блюпринтов: %d"), ProjectClasses.Num());

    // Создаем блюпринты для каждого класса
    for (UClass* Class : ProjectClasses)
    {
        if (Class)
        {
            FString BlueprintName = FString::Printf(TEXT("BP_%s"), *Class->GetName());
            CreateBlueprintFromClass(Class, BlueprintName);
        }
    }

    UE_LOG(LogTemp, Warning, TEXT("? Создание всех блюпринтов завершено!"));
}

bool UBlueprintManager::CreateBlueprintFromClass(UClass* SourceClass, const FString& BlueprintName, const FString& PackagePath)
{
    if (!SourceClass)
    {
        UE_LOG(LogTemp, Error, TEXT("? Неверный исходный класс для создания блюпринта!"));
        return false;
    }

    UE_LOG(LogTemp, Warning, TEXT("??? Создаем блюпринт %s из класса %s"),
        *BlueprintName, *SourceClass->GetName());

    // Здесь будет реальное создание блюпринта
    // Пока просто логируем
    UE_LOG(LogTemp, Warning, TEXT("   ?? Путь: %s"), *PackagePath);
    UE_LOG(LogTemp, Warning, TEXT("   ?? Класс: %s"), *SourceClass->GetName());

    return true;
}

void UBlueprintManager::EnsureBlueprintFolderExists()
{
    FString BlueprintDir = FPaths::ProjectContentDir() / TEXT("Blueprints/AutoGenerated");

    IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
    if (!PlatformFile.DirectoryExists(*BlueprintDir))
    {
        PlatformFile.CreateDirectoryTree(*BlueprintDir);
        UE_LOG(LogTemp, Warning, TEXT("?? Создана папка для блюпринтов: %s"), *BlueprintDir);
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("?? Папка для блюпринтов уже существует: %s"), *BlueprintDir);
    }
}

void UBlueprintManager::GetAllProjectClasses(TArray<UClass*>& OutClasses)
{
    // Пока возвращаем тестовые классы
    // В будущем будем автоматически находить все классы проекта

    UE_LOG(LogTemp, Warning, TEXT("?? Ищем C++ классы проекта..."));

    // Здесь будет автоматическое обнаружение классов
    // Пока возвращаем заглушку
}