#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Blueprint/BlueprintSupport.h"
#include "UObject/Package.h"
#include "Misc/PackageName.h"
#include "System1ParadoxCharacter.h"
#include "System1ParadoxGameMode.h"
#include "System1ParadoxPlayerController.h"
#include "System1ParadoxCameraManager.h"

// 🔥 ВАЖНО: .generated.h ДОЛЖЕН БЫТЬ ПОСЛЕДНИМ!
#include "BlueprintManager.generated.h"

UCLASS()
class SYSTEM1PARADOX_API UBlueprintManager : public UObject
{
    GENERATED_BODY()

public:
    UBlueprintManager();

    // Основная функция создания всех блюпринтов
    UFUNCTION(BlueprintCallable, Category = "Blueprint Automation")
    void CreateAllBlueprints();

    // Создание блюпринта из конкретного C++ класса
    UFUNCTION(BlueprintCallable, Category = "Blueprint Automation")
    bool CreateBlueprintFromClass(UClass* SourceClass, const FString& BlueprintName, const FString& PackagePath = "/Game/Blueprints/AutoGenerated");

private:
    // Создание папки для блюпринтов если не существует
    void EnsureBlueprintFolderExists();

    // Получение всех C++ классов проекта для создания блюпринтов
    void GetAllProjectClasses(TArray<UClass*>& OutClasses);

    // Проверка подходит ли класс для создания блюпринта
    bool IsClassSuitableForBlueprint(UClass* Class);
};