#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "System1ParadoxCharacter.h"
#include "System1ParadoxGameMode.h"
#include "System1ParadoxPlayerController.h"
#include "System1ParadoxCameraManager.h"

#include "BlueprintManager.generated.h"

// Предварительное объявление классов
class UEdGraph;
class UK2Node;

UCLASS()
class SYSTEM1PARADOX_API UBlueprintManager : public UObject
{
	GENERATED_BODY()

public:
	UBlueprintManager();

	// Основная функция создания всех блюпринтов
	UFUNCTION(BlueprintCallable, Category = "Blueprint Automation")
	void CreateAllBlueprints();

	// Автоматическая привязка созданных блюпринтов
	UFUNCTION(BlueprintCallable, Category = "Blueprint Automation")
	void AutoBindBlueprints();

	// Создание блюпринта из конкретного C++ класса
	UFUNCTION(BlueprintCallable, Category = "Blueprint Automation")
	bool CreateBlueprintFromClass(UClass* SourceClass, const FString& BlueprintName, const FString& PackagePath = "/Game/Blueprints/AutoGenerated");

	// 🔥 НОВАЯ ФУНКЦИЯ: Создание графов для блюпринтов
	UFUNCTION(BlueprintCallable, Category = "Blueprint Automation")
	void CreateBlueprintGraphs();

private:
	// Привязка конкретного блюпринта к настройкам проекта
	bool BindBlueprintToProject(const FString& BlueprintPath, const FString& SettingName);

	// Получение пути к блюпринту по имени класса
	FString GetBlueprintPathForClass(const FString& ClassName);

	// Принудительное сохранение конфигурации проекта
	void SaveProjectConfig();

	// Создание папки для блюпринтов если не существует
	void EnsureBlueprintFolderExists();

	// Получение всех C++ классов проекта для создания блюпринтов
	void GetAllProjectClasses(TArray<UClass*>& OutClasses);

	// Проверка подходит ли класс для создания блюпринта
	bool IsClassSuitableForBlueprint(UClass* Class);

	// 🔥 НОВЫЕ ПРИВАТНЫЕ ФУНКЦИИ ДЛЯ ГРАФОВ
	bool CreateCharacterGraphs(UBlueprint* Blueprint);
	bool CreateGameModeGraphs(UBlueprint* Blueprint);
	bool CreatePlayerControllerGraphs(UBlueprint* Blueprint);
	bool CreateCameraManagerGraphs(UBlueprint* Blueprint);

	UEdGraph* CreateEventGraph(UBlueprint* Blueprint);
	UEdGraph* CreateConstructionScript(UBlueprint* Blueprint);

	bool CreateEventBeginPlayNode(UEdGraph* EventGraph);
	bool CreateEventTickNode(UEdGraph* EventGraph);
	bool CreateConstructionScriptNodes(UEdGraph* ConstructionGraph);

	bool ConnectNodes(UEdGraph* Graph, UK2Node* FromNode, UK2Node* ToNode);
	bool CompileBlueprint(UBlueprint* Blueprint);
};