#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "System1ParadoxCharacter.h"
#include "System1ParadoxGameMode.h"
#include "System1ParadoxPlayerController.h"
#include "System1ParadoxCameraManager.h"
#include "BlueprintManager.generated.h"

UCLASS()
class SYSTEM1PARADOX_API UBlueprintManager : public UObject
{
	GENERATED_BODY()

public:
	UBlueprintManager();
	void CreateAllBlueprints();
	void AutoBindBlueprints();
	bool CreateBlueprintFromClass(UClass* SourceClass, const FString& BlueprintName, const FString& PackagePath = "/Game/Blueprints/AutoGenerated");
	void CreateBlueprintGraphs();
	void SetupCreatedBlueprints();

private:
	bool BindBlueprintToProject(const FString& BlueprintPath, const FString& SettingName);
	FString GetBlueprintPathForClass(const FString& ClassName);
	void SaveProjectConfig();
	void EnsureBlueprintFolderExists();
	void GetAllProjectClasses(TArray<UClass*>& OutClasses);
	bool IsClassSuitableForBlueprint(UClass* Class);
	bool CompileBlueprint(UBlueprint* Blueprint);
};